

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureDroppedCallback(
				UniffiForeignFutureDroppedCallback cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static uint64_t call_UniffiCallbackInterfaceClone(
				UniffiCallbackInterfaceClone cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureResultU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureResultU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureResultI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureResultI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureResultU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureResultU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureResultI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureResultI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureResultU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureResultU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureResultI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureResultI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureResultU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureResultU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureResultI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureResultI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureResultF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureResultF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureResultF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureResultF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureResultRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureResultRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureResultVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureResultVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_PROGRESS_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_PROGRESS_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceProgressCallbackMethod0)(uint64_t uniffi_handle, RustBuffer progress, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceProgressCallbackMethod0(
				UniffiCallbackInterfaceProgressCallbackMethod0 cb, uint64_t uniffi_handle, RustBuffer progress, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, progress, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_READER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_READER_METHOD0
typedef void (*UniffiCallbackInterfaceReaderMethod0)(uint64_t uniffi_handle, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceReaderMethod0(
				UniffiCallbackInterfaceReaderMethod0 cb, uint64_t uniffi_handle, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback)
{
	return cb(uniffi_handle, uniffi_future_callback, uniffi_callback_data, uniffi_out_dropped_callback);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD0
typedef void (*UniffiCallbackInterfaceLoggerMethod0)(uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLoggerMethod0(
				UniffiCallbackInterfaceLoggerMethod0 cb, uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, msg, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD1
typedef void (*UniffiCallbackInterfaceLoggerMethod1)(uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLoggerMethod1(
				UniffiCallbackInterfaceLoggerMethod1 cb, uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, msg, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD2
typedef void (*UniffiCallbackInterfaceLoggerMethod2)(uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLoggerMethod2(
				UniffiCallbackInterfaceLoggerMethod2 cb, uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, msg, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOGGER_METHOD3
typedef void (*UniffiCallbackInterfaceLoggerMethod3)(uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus );

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceLoggerMethod3(
				UniffiCallbackInterfaceLoggerMethod3 cb, uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus )
{
	return cb(uniffi_handle, msg, uniffi_out_return, callStatus );
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_PROGRESS_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_PROGRESS_CALLBACK
typedef struct UniffiVTableCallbackInterfaceProgressCallback {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceProgressCallbackMethod0 progress;
} UniffiVTableCallbackInterfaceProgressCallback;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_READER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_READER
typedef struct UniffiVTableCallbackInterfaceReader {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceReaderMethod0 read;
} UniffiVTableCallbackInterfaceReader;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOGGER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOGGER
typedef struct UniffiVTableCallbackInterfaceLogger {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceLoggerMethod0 info;
    UniffiCallbackInterfaceLoggerMethod1 warn;
    UniffiCallbackInterfaceLoggerMethod2 error;
    UniffiCallbackInterfaceLoggerMethod3 debug;
} UniffiVTableCallbackInterfaceLogger;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_DOWNLOAD
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_DOWNLOAD
uint64_t uniffi_sia_storage_ffi_fn_clone_download(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_DOWNLOAD
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_DOWNLOAD
void uniffi_sia_storage_ffi_fn_free_download(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_DOWNLOAD_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_DOWNLOAD_CANCEL
uint64_t uniffi_sia_storage_ffi_fn_method_download_cancel(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_DOWNLOAD_READ
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_DOWNLOAD_READ
uint64_t uniffi_sia_storage_ffi_fn_method_download_read(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_PACKEDUPLOAD
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_PACKEDUPLOAD
uint64_t uniffi_sia_storage_ffi_fn_clone_packedupload(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_PACKEDUPLOAD
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_PACKEDUPLOAD
void uniffi_sia_storage_ffi_fn_free_packedupload(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_ADD
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_ADD
uint64_t uniffi_sia_storage_ffi_fn_method_packedupload_add(uint64_t ptr, uint64_t reader
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_CANCEL
void uniffi_sia_storage_ffi_fn_method_packedupload_cancel(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_FINALIZE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_FINALIZE
uint64_t uniffi_sia_storage_ffi_fn_method_packedupload_finalize(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_LENGTH
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_LENGTH
uint64_t uniffi_sia_storage_ffi_fn_method_packedupload_length(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_REMAINING
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_REMAINING
uint64_t uniffi_sia_storage_ffi_fn_method_packedupload_remaining(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_SLABS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PACKEDUPLOAD_SLABS
uint64_t uniffi_sia_storage_ffi_fn_method_packedupload_slabs(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_PINNEDOBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_PINNEDOBJECT
uint64_t uniffi_sia_storage_ffi_fn_clone_pinnedobject(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_PINNEDOBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_PINNEDOBJECT
void uniffi_sia_storage_ffi_fn_free_pinnedobject(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CONSTRUCTOR_PINNEDOBJECT_NEW
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CONSTRUCTOR_PINNEDOBJECT_NEW
uint64_t uniffi_sia_storage_ffi_fn_constructor_pinnedobject_new(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CONSTRUCTOR_PINNEDOBJECT_OPEN
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CONSTRUCTOR_PINNEDOBJECT_OPEN
uint64_t uniffi_sia_storage_ffi_fn_constructor_pinnedobject_open(uint64_t app_key, RustBuffer sealed, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_CREATED_AT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_CREATED_AT
RustBuffer uniffi_sia_storage_ffi_fn_method_pinnedobject_created_at(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_ENCODED_SIZE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_ENCODED_SIZE
uint64_t uniffi_sia_storage_ffi_fn_method_pinnedobject_encoded_size(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_ID
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_ID
RustBuffer uniffi_sia_storage_ffi_fn_method_pinnedobject_id(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_METADATA
RustBuffer uniffi_sia_storage_ffi_fn_method_pinnedobject_metadata(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_SEAL
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_SEAL
RustBuffer uniffi_sia_storage_ffi_fn_method_pinnedobject_seal(uint64_t ptr, uint64_t app_key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_SIZE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_SIZE
uint64_t uniffi_sia_storage_ffi_fn_method_pinnedobject_size(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_SLABS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_SLABS
RustBuffer uniffi_sia_storage_ffi_fn_method_pinnedobject_slabs(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_UPDATE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_UPDATE_METADATA
void uniffi_sia_storage_ffi_fn_method_pinnedobject_update_metadata(uint64_t ptr, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_UPDATED_AT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PINNEDOBJECT_UPDATED_AT
RustBuffer uniffi_sia_storage_ffi_fn_method_pinnedobject_updated_at(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_PROGRESSCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_PROGRESSCALLBACK
uint64_t uniffi_sia_storage_ffi_fn_clone_progresscallback(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_PROGRESSCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_PROGRESSCALLBACK
void uniffi_sia_storage_ffi_fn_free_progresscallback(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_INIT_CALLBACK_VTABLE_PROGRESSCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_INIT_CALLBACK_VTABLE_PROGRESSCALLBACK
void uniffi_sia_storage_ffi_fn_init_callback_vtable_progresscallback(UniffiVTableCallbackInterfaceProgressCallback* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PROGRESSCALLBACK_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_PROGRESSCALLBACK_PROGRESS
void uniffi_sia_storage_ffi_fn_method_progresscallback_progress(uint64_t ptr, RustBuffer progress, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_SDK
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_SDK
uint64_t uniffi_sia_storage_ffi_fn_clone_sdk(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_SDK
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_SDK
void uniffi_sia_storage_ffi_fn_free_sdk(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_ACCOUNT
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_account(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_APP_KEY
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_APP_KEY
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_app_key(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_DELETE_OBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_DELETE_OBJECT
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_delete_object(uint64_t ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_DOWNLOAD
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_DOWNLOAD
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_download(uint64_t ptr, uint64_t object, RustBuffer options, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_HOSTS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_HOSTS
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_hosts(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_OBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_OBJECT
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_object(uint64_t ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_OBJECT_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_OBJECT_EVENTS
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_object_events(uint64_t ptr, RustBuffer cursor, uint32_t limit
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_PIN_OBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_PIN_OBJECT
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_pin_object(uint64_t ptr, uint64_t object
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_PRUNE_SLABS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_PRUNE_SLABS
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_prune_slabs(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_SHARE_OBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_SHARE_OBJECT
RustBuffer uniffi_sia_storage_ffi_fn_method_sdk_share_object(uint64_t ptr, uint64_t object, RustBuffer valid_until, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_SHARED_OBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_SHARED_OBJECT
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_shared_object(uint64_t ptr, RustBuffer shared_url
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_SLAB
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_SLAB
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_slab(uint64_t ptr, RustBuffer slab_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_UPDATE_OBJECT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_UPDATE_OBJECT_METADATA
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_update_object_metadata(uint64_t ptr, uint64_t object
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_UPLOAD
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_UPLOAD
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_upload(uint64_t ptr, uint64_t object, uint64_t r, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_UPLOAD_PACKED
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_SDK_UPLOAD_PACKED
uint64_t uniffi_sia_storage_ffi_fn_method_sdk_upload_packed(uint64_t ptr, RustBuffer options
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_APPKEY
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_APPKEY
uint64_t uniffi_sia_storage_ffi_fn_clone_appkey(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_APPKEY
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_APPKEY
void uniffi_sia_storage_ffi_fn_free_appkey(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CONSTRUCTOR_APPKEY_NEW
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CONSTRUCTOR_APPKEY_NEW
uint64_t uniffi_sia_storage_ffi_fn_constructor_appkey_new(RustBuffer key, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_APPKEY_EXPORT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_APPKEY_EXPORT
RustBuffer uniffi_sia_storage_ffi_fn_method_appkey_export(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_APPKEY_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_APPKEY_PUBLIC_KEY
RustBuffer uniffi_sia_storage_ffi_fn_method_appkey_public_key(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_APPKEY_SIGN
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_APPKEY_SIGN
RustBuffer uniffi_sia_storage_ffi_fn_method_appkey_sign(uint64_t ptr, RustBuffer message, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_APPKEY_VERIFY_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_APPKEY_VERIFY_SIGNATURE
int8_t uniffi_sia_storage_ffi_fn_method_appkey_verify_signature(uint64_t ptr, RustBuffer message, RustBuffer signature, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_BUILDER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_BUILDER
uint64_t uniffi_sia_storage_ffi_fn_clone_builder(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_BUILDER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_BUILDER
void uniffi_sia_storage_ffi_fn_free_builder(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CONSTRUCTOR_BUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CONSTRUCTOR_BUILDER_NEW
uint64_t uniffi_sia_storage_ffi_fn_constructor_builder_new(RustBuffer indexer_url, RustBuffer app_meta, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_BUILDER_CONNECTED
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_BUILDER_CONNECTED
uint64_t uniffi_sia_storage_ffi_fn_method_builder_connected(uint64_t ptr, uint64_t app_key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_BUILDER_REGISTER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_BUILDER_REGISTER
uint64_t uniffi_sia_storage_ffi_fn_method_builder_register(uint64_t ptr, RustBuffer mnemonic
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_BUILDER_REQUEST_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_BUILDER_REQUEST_CONNECTION
uint64_t uniffi_sia_storage_ffi_fn_method_builder_request_connection(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_BUILDER_RESPONSE_URL
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_BUILDER_RESPONSE_URL
RustBuffer uniffi_sia_storage_ffi_fn_method_builder_response_url(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_BUILDER_WAIT_FOR_APPROVAL
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_BUILDER_WAIT_FOR_APPROVAL
uint64_t uniffi_sia_storage_ffi_fn_method_builder_wait_for_approval(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_READER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_READER
uint64_t uniffi_sia_storage_ffi_fn_clone_reader(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_READER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_READER
void uniffi_sia_storage_ffi_fn_free_reader(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_INIT_CALLBACK_VTABLE_READER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_INIT_CALLBACK_VTABLE_READER
void uniffi_sia_storage_ffi_fn_init_callback_vtable_reader(UniffiVTableCallbackInterfaceReader* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_READER_READ
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_READER_READ
uint64_t uniffi_sia_storage_ffi_fn_method_reader_read(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_LOGGER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_CLONE_LOGGER
uint64_t uniffi_sia_storage_ffi_fn_clone_logger(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_LOGGER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FREE_LOGGER
void uniffi_sia_storage_ffi_fn_free_logger(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_INIT_CALLBACK_VTABLE_LOGGER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_INIT_CALLBACK_VTABLE_LOGGER
void uniffi_sia_storage_ffi_fn_init_callback_vtable_logger(UniffiVTableCallbackInterfaceLogger* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_LOGGER_INFO
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_LOGGER_INFO
void uniffi_sia_storage_ffi_fn_method_logger_info(uint64_t ptr, RustBuffer msg, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_LOGGER_WARN
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_LOGGER_WARN
void uniffi_sia_storage_ffi_fn_method_logger_warn(uint64_t ptr, RustBuffer msg, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_LOGGER_ERROR
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_LOGGER_ERROR
void uniffi_sia_storage_ffi_fn_method_logger_error(uint64_t ptr, RustBuffer msg, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_LOGGER_DEBUG
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_METHOD_LOGGER_DEBUG
void uniffi_sia_storage_ffi_fn_method_logger_debug(uint64_t ptr, RustBuffer msg, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FUNC_ENCODED_SIZE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FUNC_ENCODED_SIZE
uint64_t uniffi_sia_storage_ffi_fn_func_encoded_size(uint64_t size, uint8_t data_shards, uint8_t parity_shards, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FUNC_GENERATE_RECOVERY_PHRASE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FUNC_GENERATE_RECOVERY_PHRASE
RustBuffer uniffi_sia_storage_ffi_fn_func_generate_recovery_phrase(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FUNC_VALIDATE_RECOVERY_PHRASE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FUNC_VALIDATE_RECOVERY_PHRASE
void uniffi_sia_storage_ffi_fn_func_validate_recovery_phrase(RustBuffer phrase, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FUNC_SET_LOGGER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_FN_FUNC_SET_LOGGER
void uniffi_sia_storage_ffi_fn_func_set_logger(uint64_t logger, RustBuffer level, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_sia_storage_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_sia_storage_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUSTBUFFER_FREE
void ffi_sia_storage_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_sia_storage_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_U8
void ffi_sia_storage_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_U8
void ffi_sia_storage_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_U8
void ffi_sia_storage_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_sia_storage_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_I8
void ffi_sia_storage_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_I8
void ffi_sia_storage_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_I8
void ffi_sia_storage_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_sia_storage_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_U16
void ffi_sia_storage_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_U16
void ffi_sia_storage_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_U16
void ffi_sia_storage_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_sia_storage_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_I16
void ffi_sia_storage_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_I16
void ffi_sia_storage_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_I16
void ffi_sia_storage_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_sia_storage_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_U32
void ffi_sia_storage_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_U32
void ffi_sia_storage_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_U32
void ffi_sia_storage_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_sia_storage_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_I32
void ffi_sia_storage_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_I32
void ffi_sia_storage_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_I32
void ffi_sia_storage_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_sia_storage_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_U64
void ffi_sia_storage_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_U64
void ffi_sia_storage_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_U64
void ffi_sia_storage_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_sia_storage_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_I64
void ffi_sia_storage_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_I64
void ffi_sia_storage_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_I64
void ffi_sia_storage_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_sia_storage_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_F32
void ffi_sia_storage_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_F32
void ffi_sia_storage_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_F32
void ffi_sia_storage_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_sia_storage_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_F64
void ffi_sia_storage_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_F64
void ffi_sia_storage_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_F64
void ffi_sia_storage_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_sia_storage_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_sia_storage_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_sia_storage_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_sia_storage_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_sia_storage_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_POLL_VOID
void ffi_sia_storage_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_sia_storage_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_FREE_VOID
void ffi_sia_storage_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_sia_storage_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_FUNC_ENCODED_SIZE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_FUNC_ENCODED_SIZE
uint16_t uniffi_sia_storage_ffi_checksum_func_encoded_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_FUNC_GENERATE_RECOVERY_PHRASE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_FUNC_GENERATE_RECOVERY_PHRASE
uint16_t uniffi_sia_storage_ffi_checksum_func_generate_recovery_phrase(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_FUNC_VALIDATE_RECOVERY_PHRASE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_FUNC_VALIDATE_RECOVERY_PHRASE
uint16_t uniffi_sia_storage_ffi_checksum_func_validate_recovery_phrase(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_FUNC_SET_LOGGER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_FUNC_SET_LOGGER
uint16_t uniffi_sia_storage_ffi_checksum_func_set_logger(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_DOWNLOAD_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_DOWNLOAD_CANCEL
uint16_t uniffi_sia_storage_ffi_checksum_method_download_cancel(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_DOWNLOAD_READ
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_DOWNLOAD_READ
uint16_t uniffi_sia_storage_ffi_checksum_method_download_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_ADD
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_ADD
uint16_t uniffi_sia_storage_ffi_checksum_method_packedupload_add(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_CANCEL
uint16_t uniffi_sia_storage_ffi_checksum_method_packedupload_cancel(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_FINALIZE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_FINALIZE
uint16_t uniffi_sia_storage_ffi_checksum_method_packedupload_finalize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_LENGTH
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_LENGTH
uint16_t uniffi_sia_storage_ffi_checksum_method_packedupload_length(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_REMAINING
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_REMAINING
uint16_t uniffi_sia_storage_ffi_checksum_method_packedupload_remaining(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_SLABS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PACKEDUPLOAD_SLABS
uint16_t uniffi_sia_storage_ffi_checksum_method_packedupload_slabs(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_CREATED_AT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_CREATED_AT
uint16_t uniffi_sia_storage_ffi_checksum_method_pinnedobject_created_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_ENCODED_SIZE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_ENCODED_SIZE
uint16_t uniffi_sia_storage_ffi_checksum_method_pinnedobject_encoded_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_ID
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_ID
uint16_t uniffi_sia_storage_ffi_checksum_method_pinnedobject_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_METADATA
uint16_t uniffi_sia_storage_ffi_checksum_method_pinnedobject_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_SEAL
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_SEAL
uint16_t uniffi_sia_storage_ffi_checksum_method_pinnedobject_seal(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_SIZE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_SIZE
uint16_t uniffi_sia_storage_ffi_checksum_method_pinnedobject_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_SLABS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_SLABS
uint16_t uniffi_sia_storage_ffi_checksum_method_pinnedobject_slabs(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_UPDATE_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_UPDATE_METADATA
uint16_t uniffi_sia_storage_ffi_checksum_method_pinnedobject_update_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_UPDATED_AT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PINNEDOBJECT_UPDATED_AT
uint16_t uniffi_sia_storage_ffi_checksum_method_pinnedobject_updated_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PROGRESSCALLBACK_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_PROGRESSCALLBACK_PROGRESS
uint16_t uniffi_sia_storage_ffi_checksum_method_progresscallback_progress(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_ACCOUNT
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_account(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_APP_KEY
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_APP_KEY
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_app_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_DELETE_OBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_DELETE_OBJECT
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_delete_object(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_DOWNLOAD
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_DOWNLOAD
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_download(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_HOSTS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_HOSTS
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_hosts(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_OBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_OBJECT
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_object(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_OBJECT_EVENTS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_OBJECT_EVENTS
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_object_events(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_PIN_OBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_PIN_OBJECT
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_pin_object(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_PRUNE_SLABS
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_PRUNE_SLABS
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_prune_slabs(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_SHARE_OBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_SHARE_OBJECT
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_share_object(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_SHARED_OBJECT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_SHARED_OBJECT
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_shared_object(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_SLAB
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_SLAB
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_slab(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_UPDATE_OBJECT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_UPDATE_OBJECT_METADATA
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_update_object_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_UPLOAD
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_UPLOAD
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_upload(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_UPLOAD_PACKED
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_SDK_UPLOAD_PACKED
uint16_t uniffi_sia_storage_ffi_checksum_method_sdk_upload_packed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_APPKEY_EXPORT
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_APPKEY_EXPORT
uint16_t uniffi_sia_storage_ffi_checksum_method_appkey_export(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_APPKEY_PUBLIC_KEY
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_APPKEY_PUBLIC_KEY
uint16_t uniffi_sia_storage_ffi_checksum_method_appkey_public_key(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_APPKEY_SIGN
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_APPKEY_SIGN
uint16_t uniffi_sia_storage_ffi_checksum_method_appkey_sign(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_APPKEY_VERIFY_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_APPKEY_VERIFY_SIGNATURE
uint16_t uniffi_sia_storage_ffi_checksum_method_appkey_verify_signature(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_BUILDER_CONNECTED
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_BUILDER_CONNECTED
uint16_t uniffi_sia_storage_ffi_checksum_method_builder_connected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_BUILDER_REGISTER
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_BUILDER_REGISTER
uint16_t uniffi_sia_storage_ffi_checksum_method_builder_register(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_BUILDER_REQUEST_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_BUILDER_REQUEST_CONNECTION
uint16_t uniffi_sia_storage_ffi_checksum_method_builder_request_connection(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_BUILDER_RESPONSE_URL
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_BUILDER_RESPONSE_URL
uint16_t uniffi_sia_storage_ffi_checksum_method_builder_response_url(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_BUILDER_WAIT_FOR_APPROVAL
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_BUILDER_WAIT_FOR_APPROVAL
uint16_t uniffi_sia_storage_ffi_checksum_method_builder_wait_for_approval(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_READER_READ
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_READER_READ
uint16_t uniffi_sia_storage_ffi_checksum_method_reader_read(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_LOGGER_INFO
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_LOGGER_INFO
uint16_t uniffi_sia_storage_ffi_checksum_method_logger_info(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_LOGGER_WARN
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_LOGGER_WARN
uint16_t uniffi_sia_storage_ffi_checksum_method_logger_warn(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_LOGGER_ERROR
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_LOGGER_ERROR
uint16_t uniffi_sia_storage_ffi_checksum_method_logger_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_LOGGER_DEBUG
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_METHOD_LOGGER_DEBUG
uint16_t uniffi_sia_storage_ffi_checksum_method_logger_debug(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_CONSTRUCTOR_PINNEDOBJECT_NEW
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_CONSTRUCTOR_PINNEDOBJECT_NEW
uint16_t uniffi_sia_storage_ffi_checksum_constructor_pinnedobject_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_CONSTRUCTOR_PINNEDOBJECT_OPEN
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_CONSTRUCTOR_PINNEDOBJECT_OPEN
uint16_t uniffi_sia_storage_ffi_checksum_constructor_pinnedobject_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_CONSTRUCTOR_APPKEY_NEW
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_CONSTRUCTOR_APPKEY_NEW
uint16_t uniffi_sia_storage_ffi_checksum_constructor_appkey_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_CONSTRUCTOR_BUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SIA_STORAGE_FFI_CHECKSUM_CONSTRUCTOR_BUILDER_NEW
uint16_t uniffi_sia_storage_ffi_checksum_constructor_builder_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_SIA_STORAGE_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_sia_storage_ffi_uniffi_contract_version(void
    
);
#endif

 void sia_storage_ffi_cgo_dispatchCallbackInterfaceProgressCallbackMethod0(uint64_t uniffi_handle, RustBuffer progress, void* uniffi_out_return, RustCallStatus* callStatus );
 void sia_storage_ffi_cgo_dispatchCallbackInterfaceProgressCallbackFree(uint64_t handle);
uint64_t sia_storage_ffi_cgo_dispatchCallbackInterfaceProgressCallbackClone(uint64_t handle);
 void sia_storage_ffi_io_cgo_dispatchCallbackInterfaceReaderMethod0(uint64_t uniffi_handle, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback);
 void sia_storage_ffi_io_cgo_dispatchCallbackInterfaceReaderFree(uint64_t handle);
uint64_t sia_storage_ffi_io_cgo_dispatchCallbackInterfaceReaderClone(uint64_t handle);
 void sia_storage_ffi_logging_cgo_dispatchCallbackInterfaceLoggerMethod0(uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus );
 void sia_storage_ffi_logging_cgo_dispatchCallbackInterfaceLoggerMethod1(uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus );
 void sia_storage_ffi_logging_cgo_dispatchCallbackInterfaceLoggerMethod2(uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus );
 void sia_storage_ffi_logging_cgo_dispatchCallbackInterfaceLoggerMethod3(uint64_t uniffi_handle, RustBuffer msg, void* uniffi_out_return, RustCallStatus* callStatus );
 void sia_storage_ffi_logging_cgo_dispatchCallbackInterfaceLoggerFree(uint64_t handle);
uint64_t sia_storage_ffi_logging_cgo_dispatchCallbackInterfaceLoggerClone(uint64_t handle);

void sia_storage_ffi_uniffiFutureContinuationCallback(uint64_t, int8_t);
void sia_storage_ffi_uniffiFreeGorutine(uint64_t);
